replicaCount: 1
image:
  repository: ${image_repository}
  tag: ${image_tag}
resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits: { cpu: 250m, memory: 128Mi }
ingress:
  enabled: true
  className: alb
  host: ${host}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
%{ if enable_https }
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: ${certificate_arn}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
%{ else }
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
%{ endif }
